ALTER TABLE edge
DROP CONSTRAINT edge_source_id_fkey;

ALTER TABLE edge
DROP CONSTRAINT edge_target_id_fkey;

ALTER TABLE edge
ADD CONSTRAINT FK_EDGE_SOURCE_NODE_ID
    FOREIGN KEY (source_id)
    REFERENCES node(id)
    ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE edge
ADD CONSTRAINT FK_EDGE_TARGET_NODE_ID
    FOREIGN KEY (target_id)
    REFERENCES node(id)
    ON DELETE CASCADE ON UPDATE NO ACTION;